spring:
  application:
    name: demo
  datasource:
    password: ${DB_PASSWORD:274565}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/passwords}
    username: ${DB_USERNAME:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop